version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: django-part2
    container_name: django_container_part2
    command: python manage.py runserver 0.0.0.0:8000




